In [74]:
import pandas as pd

df = pd.read_csv('user_table1.csv')
df.head()

,user_name,par_id,chil_id,sp_id,price,sp_num,order_date,succ_amount,order_status,user_id,...,system,age,phonenum,sex,createtime,platform,国家,地区,城市,chann_name
0,张淑珍cBZsvu4053,KKB20200101-10,KKB20200101-10-1,sp_38059,29.0,1.0,2020/1/1,29.0,订单完成,10235253,...,Others,24,130****2771,女,1558750043481,APP,中国,华东,浙江/嘉兴,搜狗导航
1,张淑珍cBZsvu4053,KKB20200101-10,KKB20200101-10-2,sp_17975,41.8,1.0,2020/1/1,41.8,订单完成,10235253,...,Others,24,130****2771,女,1558750043481,APP,中国,华东,浙江/嘉兴,搜狗导航
2,张淑珍cBZsvu4053,KKB20200101-10,KKB20200101-10-3,sp_5422,49.0,1.0,2020/1/1,49.0,订单完成,10235253,...,Others,24,130****2771,女,1558750043481,APP,中国,华东,浙江/嘉兴,搜狗导航
3,张淑珍cBZsvu4053,KKB20200101-10,KKB20200101-10-4,sp_33467,10.5,1.0,2020/1/1,10.5,订单完成,10235253,...,Others,24,130****2771,女,1558750043481,APP,中国,华东,浙江/嘉兴,搜狗导航
4,张淑珍cBZsvu4053,KKB20200101-10,KKB20200101-10-5,sp_34732,6409.0,1.0,2020/1/1,6409.0,订单完成,10235253,...,Others,24,130****2771,女,1558750043481,APP,中国,华东,浙江/嘉兴,搜狗导航

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87818 entries, 0 to 87817
Data columns (total 21 columns):
user_name       87818 non-null object
par_id          87810 non-null object
chil_id         87810 non-null object
sp_id           87818 non-null object
price           87818 non-null float64
sp_num          87815 non-null float64
order_date      87818 non-null object
succ_amount     87815 non-null float64
order_status    87818 non-null object
user_id         87818 non-null int64
sp_name         87708 non-null object
system          87818 non-null object
age             87818 non-null int64
phonenum        87818 non-null object
sex             87818 non-null object
createtime      87818 non-null int64
platform        87818 non-null object
国家              87818 non-null object
地区              87818 non-null object
城市              87818 non-null object
chann_name      87818 non-null object
dtypes: float64(3), int64(3), object(15)
memory usage: 14.1+ MB

In [76]:
# 查看重复值
df[df.duplicated()]

,user_name,par_id,chil_id,sp_id,price,sp_num,order_date,succ_amount,order_status,user_id,...,system,age,phonenum,sex,createtime,platform,国家,地区,城市,chann_name
55506,张秀云Cme5656,KKB20200121-625,KKB20200121-625-1,sp_32710,2.6,1.0,2020/1/21,2.6,订单完成,10411001,...,IOS,22,153****2745,女,1579499179539,APP,中国,华东,福建/漳州,网易有道
55508,张秀云Cme5656,KKB20200121-625,KKB20200121-625-2,sp_22785,328.0,1.0,2020/1/21,328.0,订单完成,10411001,...,IOS,22,153****2745,女,1579499179539,APP,中国,华东,福建/漳州,网易有道
55510,张秀云Cme5656,KKB20200121-625,KKB20200121-625-3,sp_37301,99.0,1.0,2020/1/21,99.0,订单完成,10411001,...,IOS,22,153****2745,女,1579499179539,APP,中国,华东,福建/漳州,网易有道
55512,张秀云Cme5656,KKB20200121-625,KKB20200121-625-4,sp_28789,2358.0,1.0,2020/1/21,2358.0,订单完成,10411001,...,IOS,22,153****2745,女,1579499179539,APP,中国,华东,福建/漳州,网易有道
57221,左帆dmAOVI6280,KKB20200122-28,KKB20200122-28-1,sp_1592,149.0,1.0,2020/1/22,149.0,订单完成,10411430,...,PC,35,189****6036,男,1579580297364,PC,中国,华北,河北/石家庄,网易有道
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87813,潘霞n6310,KKB20200105-1412,KKB20200105-1412-5,sp_31099,10499.0,1.0,2020/1/5,10499.0,订单完成,10273367,...,Others,37,178****6226,女,1564610513296,APP,中国,中南,河南/商丘,百度关键词
87814,赵涛mocJIc3048,KKB20200104-2408,KKB20200104-2408-3,sp_23009,148.0,1.0,2020/1/4,148.0,订单完成,10338739,...,Android,50,185****3995,女,1570453894044,APP,中国,中南,河南/郸城,百度橱窗
87815,郎鹏,KKB20200107-453,KKB20200107-453-3,sp_15748,29.9,1.0,2020/1/7,29.9,订单完成,10073386,...,PC,21,186****4516,女,1521856261289,PC,中国,华东,江西/贵溪,百度关键词
87816,冯建华qtdBrw5992,KKB20200105-2183,KKB20200105-2183-1,sp_3953,13.9,1.0,2020/1/5,13.9,订单完成,10210784,...,PC,24,196****3655,女,1555620326230,PC,中国,东北,黑龙江/甘南,网易有道
87817,邱婷婷ifryf7647,KKB20200104-2245,KKB20200104-2245-1,sp_16433,138.9,1.0,2020/1/4,138.9,订单完成,10292689,...,Android,27,133****7129,男,1566721311413,APP,中国,华东,山东/泗水,新浪扶翼

In [77]:
# 处理重复值

df.drop_duplicates(inplace=True)

- 均值
- 中位数
- 众数
- 自定义数据

In [78]:
# 填充空值
df['par_id'].fillna(df['par_id'].mode()[0], inplace=True)

In [79]:
# 填充空值
df['chil_id'].fillna(df['chil_id'].mode()[0], inplace=True)

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 87487 entries, 0 to 87616
Data columns (total 21 columns):
user_name       87487 non-null object
par_id          87487 non-null object
chil_id         87487 non-null object
sp_id           87487 non-null object
price           87487 non-null float64
sp_num          87484 non-null float64
order_date      87487 non-null object
succ_amount     87484 non-null float64
order_status    87487 non-null object
user_id         87487 non-null int64
sp_name         87378 non-null object
system          87487 non-null object
age             87487 non-null int64
phonenum        87487 non-null object
sex             87487 non-null object
createtime      87487 non-null int64
platform        87487 non-null object
国家              87487 non-null object
地区              87487 non-null object
城市              87487 non-null object
chann_name      87487 non-null object
dtypes: float64(3), int64(3), object(15)
memory usage: 14.7+ MB

In [81]:
# 删除空值
df.dropna(inplace=True)

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 87372 entries, 0 to 87616
Data columns (total 21 columns):
user_name       87372 non-null object
par_id          87372 non-null object
chil_id         87372 non-null object
sp_id           87372 non-null object
price           87372 non-null float64
sp_num          87372 non-null float64
order_date      87372 non-null object
succ_amount     87372 non-null float64
order_status    87372 non-null object
user_id         87372 non-null int64
sp_name         87372 non-null object
system          87372 non-null object
age             87372 non-null int64
phonenum        87372 non-null object
sex             87372 non-null object
createtime      87372 non-null int64
platform        87372 non-null object
国家              87372 non-null object
地区              87372 non-null object
城市              87372 non-null object
chann_name      87372 non-null object
dtypes: float64(3), int64(3), object(15)
memory usage: 14.7+ MB

In [83]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 87372 entries, 0 to 87616
Data columns (total 21 columns):
user_name       87372 non-null object
par_id          87372 non-null object
chil_id         87372 non-null object
sp_id           87372 non-null object
price           87372 non-null float64
sp_num          87372 non-null float64
order_date      87372 non-null datetime64[ns]
succ_amount     87372 non-null float64
order_status    87372 non-null object
user_id         87372 non-null int64
sp_name         87372 non-null object
system          87372 non-null object
age             87372 non-null int64
phonenum        87372 non-null object
sex             87372 non-null object
createtime      87372 non-null int64
platform        87372 non-null object
国家              87372 non-null object
地区              87372 non-null object
城市              87372 non-null object
chann_name      87372 non-null object
dtypes: datetime64[ns](1), float64(3), int64(3), object(14)
memory usage: 14.7+ MB

In [85]:
def func1(x):
    l = x.split('/')
    return l[0]
def func2(x):
    l = x.split('/')
    return l[1]
df['省份'] = df['城市'].apply(func1)
df['城市'] = df['城市'].apply(func2)

In [86]:
df.head()

,user_name,par_id,chil_id,sp_id,price,sp_num,order_date,succ_amount,order_status,user_id,...,age,phonenum,sex,createtime,platform,国家,地区,城市,chann_name,省份
0,张淑珍cBZsvu4053,KKB20200101-10,KKB20200101-10-1,sp_38059,29.0,1.0,2020-01-01,29.0,订单完成,10235253,...,24,130****2771,女,1558750043481,APP,中国,华东,嘉兴,搜狗导航,浙江
1,张淑珍cBZsvu4053,KKB20200101-10,KKB20200101-10-2,sp_17975,41.8,1.0,2020-01-01,41.8,订单完成,10235253,...,24,130****2771,女,1558750043481,APP,中国,华东,嘉兴,搜狗导航,浙江
2,张淑珍cBZsvu4053,KKB20200101-10,KKB20200101-10-3,sp_5422,49.0,1.0,2020-01-01,49.0,订单完成,10235253,...,24,130****2771,女,1558750043481,APP,中国,华东,嘉兴,搜狗导航,浙江
3,张淑珍cBZsvu4053,KKB20200101-10,KKB20200101-10-4,sp_33467,10.5,1.0,2020-01-01,10.5,订单完成,10235253,...,24,130****2771,女,1558750043481,APP,中国,华东,嘉兴,搜狗导航,浙江
4,张淑珍cBZsvu4053,KKB20200101-10,KKB20200101-10-5,sp_34732,6409.0,1.0,2020-01-01,6409.0,订单完成,10235253,...,24,130****2771,女,1558750043481,APP,中国,华东,嘉兴,搜狗导航,浙江

In [87]:
# df.to_csv('table_change.csv')

In [112]:
# 排序函数
def order_sort(group):
    return group.sort_values(by='order_date')[-1:]


# 将数据按客户ID分组
df_group = df.groupby(by='user_id', as_index=False)
# 将每个分组对象的数据排序，并取出日期最大的数据
data_max_time = df_group.apply(order_sort)
# print(data_max_time)

# 为数据添加F列
data_max_time['F'] = df_group.size().values
# 为数据添加M列
data_max_time['M'] = df_group.sum()['succ_amount'].values
# print(data_max_time)

# 确定统计日期
stat_date = pd.to_datetime('2020-1-31')
# 计算最近一次交易时间的间隔
r_data = stat_date - data_max_time['order_date']
# 为数据添加R列
data_max_time['R'] = r_data.values
# print(data_max_time)

section_list_F = [0, 2, 4, 6, 8, 25]
# 根据区间设置评分
grade_F = pd.cut(data_max_time['F'],
                 bins=section_list_F,
                 labels=[1, 2, 3, 4, 5])
# 添加FS评分列
data_max_time['F_S'] = grade_F.values

# 设置M维度的评分
section_list_M = [0, 200, 500, 1000, 5000, 100000]
# 根据区间设置评分
grade_M = pd.cut(data_max_time['M'],
                 bins=section_list_M,
                 labels=[1, 2, 3, 4, 5])
# 添加MS评分列
data_max_time['M_S'] = grade_M.values

# 设置R维度的评分
import datetime
section_list_R = [
    datetime.timedelta(days=i) for i in [-1, 3, 7, 15, 20, 30]
]
# 根据区间设置评分
grade_R = pd.cut(data_max_time['R'],
                 bins=section_list_R,
                 labels=[5, 4, 3, 2, 1])
# 添加RS评分列
data_max_time['R_S'] = grade_R.values

# 设置F维度高低值
data_max_time['F_S'] = data_max_time['F_S'].values.astype('int')
# 根据评分平均分设置判别高低
grade_avg = data_max_time['F_S'].values.sum() / data_max_time['F_S'].count()
# 将高对应为1，低设置为0
data_F_S = data_max_time['F_S'].where(data_max_time['F_S'] >= grade_avg, 0)
data_max_time['F_high-low'] = data_F_S.where(data_max_time['F_S'] < grade_avg,
                                             1).values

# 设置M维度高低值
data_max_time['M_S'] = data_max_time['M_S'].values.astype('int')
# 根据评分平均分设置判别高低
grade_avg = data_max_time['M_S'].values.sum() / data_max_time['M_S'].count()
# 将高对应为1，低设置为0
data_M_S = data_max_time['M_S'].where(data_max_time['M_S'] >= grade_avg, 0)
data_max_time['M_high-low'] = data_M_S.where(data_max_time['M_S'] < grade_avg,
                                             1).values

# 设置R维度高低值
data_max_time['R_S'] = data_max_time['R_S'].values.astype('int')
# 根据评分平均分设置判别高低
grade_avg = data_max_time['R_S'].values.sum() / data_max_time['R_S'].count()
# 将高对应为1，低设置为0
data_R_S = data_max_time['R_S'].where(data_max_time['R_S'] >= grade_avg, 0)
data_max_time['R_high-low'] = data_R_S.where(data_max_time['R_S'] < grade_avg,
                                             1).values

# 截取部分列数据
data_rfm = data_max_time[[
    'user_id', 'R_high-low', 'F_high-low', 'M_high-low'
]]


def get_sum_value(series):
    return ''.join([str(i) for i in series.values.tolist()[1:]])


# 添加RFM字符串列
data_rfm['data_rfm'] = data_rfm.apply(get_sum_value, axis=1)
dic = {
    '111': '重要价值客户',
    '011': '重要保持客户',
    '001': '重要挽留客户',
    '101': '重要发展客户',
    '010': '一般保持客户',
    '110': '一般价值客户',
    '000': '一般挽留客户',
    '100': '一般发展客户'
}
# RFM字符串数据映射成对应类型文字
data_rfm['data_rfm'] = data_rfm['data_rfm'].map(dic)
# print(data_rfm)

/Users/seven/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:93: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/seven/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [113]:
data_rfm['data_rfm'].value_counts()

一般发展客户    6065
一般挽留客户    6027
重要价值客户    5333
重要保持客户    4533
重要挽留客户    2277
重要发展客户    2264
一般价值客户    1292
一般保持客户    1165
Name: data_rfm, dtype: int64

In [111]:
data_max_time['M'].max()

542873.3

In [101]:
data_max_time.head(100)

,,user_name,par_id,chil_id,sp_id,price,sp_num,order_date,succ_amount,order_status,user_id,...,省份,F,M,R,F_S,M_S,R_S,F_high-low,M_high-low,R_high-low
0,81546,谭科,KKB20200130-1395,KKB20200130-1395-1,sp_29133,13899.0,1.0,2020-01-30,13899.0,订单完成,10000024,...,湖北,1,13899.0,1 days,1,5,5,0,1,1
1,3494,一粒安,KKB20200102-520,KKB20200102-520-2,sp_50410,79.0,1.0,2020-01-02,79.0,订单完成,10000056,...,天津,4,1163.0,29 days,2,4,1,1,1,0
2,24147,UILYYh,KKB20200103-1522,KKB20200103-1522-3,sp_35371,429.0,1.0,2020-01-03,429.0,订单完成,10000062,...,山东,3,1304.0,28 days,2,4,1,1,1,0
3,47171,黑猫紧支,KKB20200117-195,KKB20200117-195-5,sp_18597,8.9,1.0,2020-01-17,8.9,订单完成,10000085,...,吉林,5,851.9,14 days,3,3,3,1,1,1
4,43738,束传贲,KKB20200115-535,KKB20200115-535-4,sp_26329,145.0,1.0,2020-01-15,145.0,订单完成,10000093,...,广东,4,703.0,16 days,2,3,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,42845,羿慎刚,KKB20200115-1949,KKB20200115-1949-1,sp_646,3350.0,1.0,2020-01-15,3350.0,订单完成,10001380,...,山东,1,3350.0,16 days,1,4,2,0,1,0
96,76922,蒲应,KKB20200129-1025,KKB20200129-1025-1,sp_19070,85.0,1.0,2020-01-29,85.0,订单完成,10001397,...,黑龙江,1,85.0,2 days,1,1,5,0,1,1
97,35227,cGWejqI,KKB20200110-671,KKB20200110-671-3,sp_27661,105.0,1.0,2020-01-10,105.0,订单完成,10001419,...,辽宁,3,1733.0,21 days,2,4,1,1,1,0
98,25157,陈亚栋,KKB20200102-1572,KKB20200102-1572-1,sp_2223,1555.0,2.0,2020-01-02,3110.0,订单完成,10001451,...,四川,1,3110.0,29 days,1,4,1,0,1,0
99,47625,辛玲,KKB20200117-538,KKB20200117-538-1,sp_31027,10299.0,1.0,2020-01-17,10299.0,订单完成,10001453,...,山东,1,10299.0,14 days,1,5,3,0,1,1

In [97]:
data_max_time.describe()

,price,sp_num,succ_amount,user_id,age,createtime,F,M,R,F_S,M_S,R_S,F_high-low,M_high-low,R_high-low
count,28956.000000,28956.000000,28956.000000,2.895600e+04,28956.000000,2.895600e+04,28956.000000,28956.000000,28956,28956.000000,2.895600e+04,28956.000000,28956.000000,28956.000000,28956.000000
mean,846.398828,1.535191,943.037185,1.020484e+07,35.490227,1.548554e+12,3.017406,2826.199472,14 days 13:04:44.956485,1.798764,-3.790514e+16,2.693570,0.425577,0.995890,0.516439
std,5158.526795,1.512204,5255.079022,1.177463e+05,10.711923,2.500068e+10,2.460106,8150.680536,9 days 14:23:13.942820,1.136032,5.900749e+17,1.482926,0.494439,0.063976,0.499738
min,-59.800000,1.000000,-59.800000,1.000002e+07,18.000000,1.483214e+12,1.000000,0.690000,0 days 00:00:00,1.000000,-9.223372e+18,1.000000,0.000000,0.000000,0.000000
25%,49.900000,1.000000,61.597500,1.010418e+07,26.000000,1.538005e+12,1.000000,198.800000,5 days 00:00:00,1.000000,1.000000e+00,1.000000,0.000000,1.000000,0.000000
50%,138.000000,1.000000,169.000000,1.020465e+07,35.000000,1.555228e+12,2.000000,996.000000,15 days 00:00:00,1.000000,3.000000e+00,3.000000,0.000000,1.000000,1.000000
75%,455.000000,1.000000,690.500000,1.030714e+07,44.000000,1.568365e+12,4.000000,3377.425000,24 days 00:00:00,2.000000,4.000000e+00,4.000000,1.000000,1.000000,1.000000
max,540000.000000,30.000000,540000.000000,1.041492e+07,60.000000,1.580258e+12,23.000000,542873.300000,30 days 00:00:00,5.000000,5.000000e+00,5.000000,1.000000,1.000000,1.000000